[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://heqrqvmvacpczngdxjzo.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_DOjgadiPTCgOyNigwcCUKQ_djxtTupQ"

[[plugins]]
  package = "@netlify/plugin-nextjs"
